<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StudentManagement.Core\StudentManagement.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ElBruno.LocalEmbeddings" Version="1.5.0" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.17.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.8.3" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.8.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
    <PackageReference Include="OpenAI" Version="2.12.0" />
    <PackageReference Include="Qdrant.Client" Version="1.19.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
